language: java

dist: trusty

sudo: false

jdk:
 - oraclejdk8

before_script:
 - "Xvfb :99 &"
 - "export DISPLAY=:99"

install:
 - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
 - mvn test

cache:
  directories:
   - $HOME/.m2
