language: java

dist: trusty

sudo: false

jdk:
 - oraclejdk8
 
before install:
- mvn -f /pom.xml

install:
 - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script: 
 - mvn test -B
